services:
  id-db:
    image: postgres
    container_name: id-db
    environment:
      - POSTGRES_USER=identity
      - POSTGRES_DB=identity
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - id-db-data:/var/lib/postgresql
    profiles: 
      - id
  orders-db:
    image: postgres
    container_name: orders-db
    environment:
      - POSTGRES_USER=orders
      - POSTGRES_DB=orders
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
    volumes:
      - orders-db-data:/var/lib/postgresql
    profiles: 
      - order
  inventory-db:
    image: postgres
    container_name: inventory-db
    environment:
      - POSTGRES_USER=inventory
      - POSTGRES_DB=inventory
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5434:5432"
    volumes:
      - inventory-db-data:/var/lib/postgresql
    profiles: 
      - inventory
  rabbit-mq:
    image: rabbitmq:4.3-management-alpine
    container_name: mq-main
    hostname: main-hub
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    profiles:
      - id
      - order
      - inventory
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: keycloak
    command: start
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTP_ENABLED=false
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/certs/cert.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/certs/key.pem
      - KC_HOSTNAME=localhost
      - KC_HTTPS_PORT=8443
    ports:
      - 127.0.0.1:8443:8443
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./certs:/opt/keycloak/certs:ro
    profiles:
      - id
      - order

volumes:
  id-db-data:
  orders-db-data:
  inventory-db-data:
  keycloak-data: