<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet Package Settings -->
    <PackageId>Shared.DependencyInjection</PackageId>
    <Version>1.0.0</Version>
    <Authors>Upen Dhakal</Authors>
    <Company>Checkout</Company>
    <Description>Extention methods to allow dependency injection</Description>
    <PackageTags>checkout;common;shared</PackageTags>

    <!-- Optional: Repository metadata -->
    <RepositoryUrl>https://github.com/dhakalu/checkout</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

 <ItemGroup>
  <ProjectReference Include="../Shared.Annotations/Shared.Annotations.csproj" />
  <ProjectReference Include="../Shared.Exceptions/Shared.Exceptions.csproj" />
 </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
  </ItemGroup>

</Project>