<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet Package Settings -->
    <PackageId>Shared.Exceptions</PackageId>
    <Version>1.0.0</Version>
    <Authors>Upen Dhakal</Authors>
    <Company>Checkout</Company>
    <Description>Utilities for exceptions that are shared across projects</Description>
    <PackageTags>checkout;common;shared;exceptions</PackageTags>

    <!-- Optional: Repository metadata -->
    <RepositoryUrl>https://github.com/dhakalu/checkout</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

</Project>